server:
  port : 8081

#============================================================================
# SPRING
#============================================================================
spring:
  application:
    name: slr-api
#  profiles:
#    active : prod
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://${db.host}:${db.port}/${db.name}?autoReconnect=${db.auto-reconnect}&useSSL=${db.ssl}&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username : ${db.username}
    password : ${db.password}
  jpa:
    show-sql: false
    properties:
          hibernate:
            dialect : org.hibernate.dialect.MySQL5Dialect
            ddl-auto : validate     # Hibernate ddl auto (create, create-drop, validate, update)
  flyway:
    enabled: true

#============================================================================
# DATABASE
#============================================================================
db:
  name : slr
  host : slr-mysql
  port : 3306
  username : slr
  password : password
  auto-reconnect : true
  ssl : false