server:
  port : 8080

spring:
  devtools:
    restart:
      enabled : true

logging:
  level:
#    web : DEBUG
    com:
      wissensalt:
        rnd:
          slr:
            web:
              feign: DEBUG

api:
  base-path : http://slr-api:8081